
# fleetautoscaler.yaml

# Reference
# https://agones.dev/site/docs/reference/fleetautoscaler/

apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: fleet-autoscaler
spec:
  fleetName: simple-node-app-fleet
  policy:
    type: Buffer
    buffer:
      bufferSize: 2
      minReplicas: 2
      maxReplicas: 10