# modified-install.yaml
# Docs: https://github.com/Octops/gameserver-ingress-controller

---
apiVersion: v1
kind: Namespace
metadata:
  name: octops-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: octops
  namespace: octops-system
  labels:
    app: octops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: octops
  labels:
    app: octops
rules:
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "create" ]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "watch"]
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "list", "get", "create", "delete", "watch" ]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["list", "get", "create", "delete", "watch"]
  - apiGroups: ["agones.dev"]
    resources: ["gameservers","fleets"]
    verbs: ["get", "update", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: octops
  labels:
    app: octops
subjects:
  - kind: User
    name: system:serviceaccount:octops-system:octops
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: octops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: octops-ingress-controller
  name: octops-ingress-controller
  namespace: octops-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: octops-ingress-controller
  template:
    metadata:
      labels:
        app: octops-ingress-controller
    spec:
      serviceAccountName: octops
      containers:
        - image: octops/gameserver-ingress-controller:0.2.1 # Latest release
          name: controller
          ports:
            - containerPort: 30235
              name: healthz
            - containerPort: 9090
              name: metrics
          args:
            - --sync-period=15s
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.05" # Reduced from 0.5
              memory: "30Mi" # Reduced from 50Mi
            limits:
              cpu: "0.25" # Reduced from 1
              memory: "100Mi" # Reduced from 150Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 30235
          readinessProbe:
            httpGet:
              path: /healthz
              port: 30235