# certificate-clouddns.yaml
# docs: https://cert-manager.io/docs/configuration/acme/dns01/google/#create-an-issuer-that-uses-clouddns

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: project-yourdomain-com # Certificate name, select your own
  namespace: default
spec:
  secretName: wildcard-cert # Referenced in fleet/gameserver manifest
  issuerRef:
    name: clouddns-issuer # Reference issuer 
  dnsNames:
  - "*.YOURDOMAIN.com"
