# issuer-dns01.yaml
# docs: https://cert-manager.io/docs/configuration/acme/dns01/google/#create-an-issuer-that-uses-clouddns

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: clouddns-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: YOUR_EMAIL # example: your@email.com
    privateKeySecretRef:
      name: acme-account-secret # This can be anything
    solvers:
    - dns01:
      cloudDNS:
        project: YOUR_GCP_PROJECT # your gcp-project
        serviceAccountSecretRef:
          name: YOUR_SECRET_NAME # example: clouddns-dns01-solver-svc-acct
          key: YOUR_SECRET_KEY # example: FILENAME.json
